#!/bin/sh

host=`echo $1|sed -re "s|^.{0,10}:?//||" -e "s|/.*$||"`
if test -z $host
then
	echo "Usage: `basename $0` URL [wget options]"
	exit 1
fi
#echo "Host: $host"

while true
do
	wget --timeout=120 -c "$@"
	
	case $? in
		0)exit 0;;
		1|4|5|7):;;
		*)exit $?;;
	esac

	echo

	while ! ping -c1 $host
	do sleep 1
	done
done
